version: "3"

services:
  vote:
    image: vote
    volumes:
     - ./vote:/app
    ports:
     - "80"
    expose:
     - "80"
    networks:
     - front-tier
     - back-tier
 
  nginx:
    build:
      context: ./nginx
    depends_on:
      - vote
    ports:
      - "80:80"
    networks:
      - front-tier

  redis:
    image: redis:alpine
    ports: ["6379"]
    networks:
     - back-tier

  worker:
    image: worker
    networks:
     - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
     - back-tier 

  result:
    image: result
    volumes:
     - ./result:/app
    ports:
     - "5001:80"
     - "5858:5858"
    networks:
     - front-tier
     - back-tier

networks:
  front-tier:
  back-tier:
