version: "3"

services:
  vote:
    image: example-voting-app_vote
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    image: example-voting-app_worker

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  result:
    image: example-voting-app_result
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
